name: 使用抱脸创建Music

on:
  workflow_dispatch:
    inputs:
      Token:
        description: '抱脸Token（需要写权限）'
        required: true
      image:
        description: 'Docker镜像地址'
        required: false
        default: ''
      git_url:
        description: '代理服务'
        required: false
        default: ''
      password:
        description: '管理员密码'
        required: true
      git_token:
        description: 'GitHub Token'
        required: true
      webdav_url:
        description: 'WebDAV 地址'
        required: true
      webdav_user:
        description: 'WebDAV 用户名'
        required: true
      webdav_pass:
        description: 'WebDAV 密码'
        required: true

jobs:
  build:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0 
          
      - name: 隐藏输入信息
        uses: levibostian/action-hide-sensitive-inputs@v1
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip wheel
          pip install huggingface_hub

      - name: 检查系统依赖
        run: |
          python -V

      - name: 运行脚本
        run: |
          python music.py \
            --token "${{ github.event.inputs.Token }}" \
            --image "${{ github.event.inputs.image }}" \
            --git-url "${{ github.event.inputs.git_url }}" \
            --git-token "${{ github.event.inputs.git_token }}" \
            --password "${{ github.event.inputs.password }}" \
            --webdav-url "${{ github.event.inputs.webdav_url }}" \
            --webdav-user "${{ github.event.inputs.webdav_user }}" \
            --webdav-pass "${{ github.event.inputs.webdav_pass }}"
